config/routes.rb
Rails.application.routes.draw do
  root :to => "welcome#index"

  get '/users/logout' => "users#logout"
  get '/users/login' => "users#login"
  post '/login_user' => "users#login_user"

  post '/up_question_votes' => "votes#up_question_vote", as: "Up_question_vote"
  post '/down_question_votes' => "votes#down_question_vote", as: "Down_question_vote"
  post '/answers/:answer_id/up_answer_votes' => "votes#up_answer_vote", as: "Up_answer_vote"
  post '/answers/:answer_id/down_answer_votes' => "votes#down_answer_vote", as: "Down_answer_vote"


  resources :users, shallow: true do
    resources :questions
    resources :answers
    resources :comments
  end

  resources :questions, shallow: true do
    resources :answers
    resources :comments
  end

  resources :answers, shallow: true do
    resources :comments
  end
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :user
  belongs_to :question
  has_many :comments, as: :commentable
  has_many :votes, as: :voteable

  validates :content, presence:true

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :commentable, polymorphic:true

  validates :content, presence: true
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  has_many :answers
  has_many :comments, as: :commentable
  has_many :votes, as: :voteable

  validates :title, presence:true
  validates :title, length: { maximum: 140 }
  validates :content, presence:true

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, :username, :password, :email, presence:true
  validates :username, :email, uniqueness:true
  validates :password, length: { in: 6..30 }
  validates :name, :username, :email, length: { maximum: 30 }
  validates_format_of :email, with: /@/

  has_many :questions
  has_many :answers
  has_many :comments
  has_many :votes
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :voteable, polymorphic: true

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def new
    @answer = Answer.new
  end

  def create
    @answer = Answer.new(question_id: params[:question_id], user_id: session[:user_id], content: params[:answer][:content])
    p @answer
    if @answer.save
      redirect_to @answer.question
    else
      redirect_to "/questions/#{params[:question_id]}/answers/new"
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    if params[:question_id]
      @question = Question.find(params[:question_id])
    elsif params[:answer_id]
      @answer = Answer.find(params[:answer_id])
    end
  end

  def create
    commentable_id = params[:question_id] ||= params[:answer_id]
    if params[:answer_id]
      commentable_type = "Answer"
    else
      commentable_type = "Question"
    end
    @comment = Comment.new(content: params[:comment][:content],
                           user_id: session[:user_id],
                           commentable_id: commentable_id,
                           commentable_type: commentable_type)
    if @comment.save
      user = User.find(session[:user_id])
      user.comments << @comment
      if @comment.commentable_type == "Question"
        question = Question.find(params[:question_id])
        question.comments << @comment
        redirect_to question_path(question.id)
      elsif @comment.commentable_type == "Answer"
        answer = Answer.find(params[:answer_id])
        answer.comments << @comment
        redirect_to question_path(answer.question.id)
      end
    else
      render 'new'
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
  end

  def new
    @question = Question.new
  end

  #show is serving as the new controller for now
  def show
    @question = Question.find(params[:id])
    session[:question_id] = @question.id
    @answers = @question.answers
    @comments = @question.comments
  end

  def create
    @question = Question.new(question_params)
    user = User.find(session[:user_id])
    @question.user = user
    if @question.save
      # flash[:success] = "Welcome to the Sample App!"
      redirect_to @question
    else
      render 'new'
    end
  end


  private

  def question_params
    params.require(:question).permit(:title, :content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @questions = @user.questions
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to the Sample App!"
      session[:user_id] = @user.id
      p session[:user_id]
      redirect_to @user
    else
      render 'new'
    end
  end

  def login

  end

  def login_user
    @user = User.find_by_username(params[:username])
    if @user && @user.password == params[:password]
      session[:user_id] = @user.id
      @error = false
      redirect_to @user
    else
      @error = true
      render 'login'
    end
  end

  def logout
    session[:user_id] = nil
    redirect_to root_path
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :username)
    end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def up_question_vote
    previous_vote = current_user_vote("Question", session[:question_id])
    if previous_vote == nil
      @vote = Vote.create(upvote: true, user_id: session[:user_id], voteable_id: session[:question_id], voteable_type: "Question")
      redirect_to "/questions/#{session[:question_id]}"
    else
      new_vote = Vote.find(previous_vote.id)
      new_vote.upvote = true
      new_vote.save
      redirect_to "/questions/#{session[:question_id]}"
    end
  end

  def down_question_vote
    previous_vote = current_user_vote("Question", session[:question_id])
    if previous_vote == nil
      @vote = Vote.create(upvote: false, user_id: session[:user_id], voteable_id: session[:question_id], voteable_type: "Question")
      redirect_to "/questions/#{session[:question_id]}"
    else
      new_vote = Vote.find(previous_vote.id)
      new_vote.upvote = false
      new_vote.save
      redirect_to "/questions/#{session[:question_id]}"
    end
  end

  def up_answer_vote
    previous_vote = current_user_vote("Answer", params[:answer_id])
    if previous_vote == nil
      @vote = Vote.create(upvote: true, user_id: session[:user_id], voteable_type: "Answer", voteable_id: params[:answer_id])
      redirect_to "/questions/#{session[:question_id]}"
    else
      new_vote = Vote.find(previous_vote.id)
      new_vote.upvote = true
      new_vote.save
      redirect_to "/questions/#{session[:question_id]}"
    end
  end

  def down_answer_vote
    previous_vote = current_user_vote("Answer", params[:answer_id])
    if previous_vote == nil
      @vote = Vote.create(upvote: false, user_id: session[:user_id], voteable_type: "Answer", voteable_id: params[:answer_id])
      redirect_to "/questions/#{session[:question_id]}"
    else
      new_vote = Vote.find(previous_vote.id)
      new_vote.upvote = false
      new_vote.save
      redirect_to "/questions/#{session[:question_id]}"
    end
  end

  private
  def current_user_vote(voteable_type, voteable_id)
    if voteable_type == 'Question'
      user_votes = User.find(session[:user_id]).votes
      previous_vote = user_votes.where(votes: {voteable_type: "Question", voteable_id: voteable_id}).first
    else
      user_votes = User.find(session[:user_id]).votes
      previous_vote = user_votes.where(votes: {voteable_type: "Answer", voteable_id: voteable_id}).first
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)

    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

  def score_of_votes(object)
    counter = 0
    object.votes.each do |vote|
      if vote.upvote == true
        counter += 1
      else
        counter -= 1
      end
    end
    counter
  end

end

app/views/answers/new.html.erb
<%= form_for @answer do |a| %>
<p>
  <%= a.label :content %>
  <%= a.text_area :content %>
</p>
<p>
  <input type="hidden" name="question_id" value="<%= params[:question_id] %>" />
</p>
<p><%= a.submit :create %></p>
<% end %>

app/views/comments/new.html.erb
<% if @question %>
  <h1>Comment on '<%=@question.title%>' </h1>

  <div class="row">
    <div class="span6 offset3">
      <%= form_for [@question, Comment.new] do |f| %>
        <%= f.label :content %>
        <%= f.text_field :content %>
        <%= f.submit "Post my Comment", class: "btn btn-large btn-primary" %>
      <% end %>
    </div>
  </div>

<% elsif @answer %>
  <h1>Comment on '<%=@answer.content%>' </h1>

  <div class="row">
    <div class="span6 offset3">
      <%= form_for [@answer, Comment.new] do |f| %>
        <%= f.label :content %>
        <%= f.text_field :content %>
        <%= f.submit "Post my Comment", class: "btn btn-large btn-primary" %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Quack Overflow</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'application', 'https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<h4 style="margin: 10px 10px 5px 10px"> Quack Overflow </h4>
<header style="margin: 5px 10px;">
  <%=
   link_to_if(session[:user_id].nil?, "Login", { controller: "users", action: "login" }) do
     link_to("Log Out", { controller: "users", action: "logout", id: session[:user_id] })
   end
%>

<%=
   link_to_if(session[:user_id].nil?, "Sign Up", { controller: "users", action: "new" }) do
     link_to("My Account", { controller: "users", action: "show", id: session[:user_id] })
   end
%>
<%= link_to "Home", root_path %>
</header>
<body>

  <div class="container">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
    <%= yield %>
  </div>
<footer>
  <p style="margin: 10px">All Rights Reserved. Brought to you by The Quacks.</p>
</footer>
</body>
</html>

app/views/questions/index.html.erb
<% @questions.each do |question| %>
  <h3><%= link_to question.title, question_path(question.id) %></h3>
<% end %>

app/views/questions/new.html.erb
<% provide(:title, 'Ask a Question') %>
<h1>Ask a Question</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for @question do |f| %>
      <%= f.label :title %>
      <%= f.text_field :title %>

      <%= f.label :content %>
      <%= f.text_field :content %>

      <%= f.submit "Ask my Question", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/questions/show.html.erb
<% provide(:title, @question.title) %>
<h1>
  <%= score_of_votes(@question) %> - <%= @question.title%>
</h1>
<%if session[:user_id] %>
  <%= link_to image_tag('duck_up.png', height: 'auto', width: '8%', class: 'duck-up'), '/up_question_votes', method: :post %>
  <%= link_to image_tag('duck_down.png', height: 'auto', width: '8%', class: 'duck-up'), '/down_question_votes', method: :post %>
<% end %>
<h4>
  <%= @question.content %>
</h4>
<h5>
  created by: <%= @question.user.username %>
</h5>
<h6>
  <% @comments.each do |comment| %>
    <%= comment.content %> - <%= comment.user.username %> <br>
  <% end %>
</h6>

<% if session[:user_id] %>
  <%= link_to 'Comment', new_question_comment_path(@question) %>
<% end %>

<% if session[:user_id] %>
  <form action="/questions/<%= params[:id] %>/answers/new" method="get">
    <input type="submit" value="Answer">
  </form>
<% end %>


<% if @answers %>
  <% @answers.each_with_index do |answer, i| %>
    <h3><%= score_of_votes(answer) %> - Answer <%= i+1 %>:  <%= answer.content %><h3>
    <% if session[:user_id] %>
      <h5><%= link_to image_tag('duck_up.png', height: 'auto', width: '8%', class: 'duck-up'), Up_answer_vote_path(answer), method: :post %>
      <%= link_to image_tag('duck_down.png', height: 'auto', width: '8%', class: 'duck-up'), Down_answer_vote_path(answer), method: :post %></h5>
    <% end %>

    <h6>
      <% answer.comments.each do |comment| %>
        <%= comment.content %> - <%= comment.user.username %> <br>
      <% end %>
    </h6>

    <% if session[:user_id] %>
      <%= link_to 'Comment', new_answer_comment_path(answer) %>
    <% end %>
  <% end %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/index.html.erb
<% @users.each do |user| %>
  <h3><%= link_to user.username, user_path(user.id) %></h3>

<% end %>

app/views/users/login.html.erb
<% provide(:title, 'Login') %>
<h1>Log In</h1>

<div class="row">
  <div class="span6 offset3">
    <% if @error %>
      <p>Username or password is incorrect. Please try again!</p>
    <% end %>
    <%= form_tag '/login_user' do -%>

      <%= label_tag :username, 'Username: ' %><br>
      <%= text_field_tag :username %><br>

      <%= label_tag :password, 'Password: ' %><br>
      <%= password_field_tag :password %><br>

      <%= submit_tag 'Login' %>

    <% end %>

  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
       <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :username %>
      <%= f.text_field :username %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
  <% provide(:title, @user.name) %>
  <h1>
    <%= gravatar_for @user %>
    <%= @user.name %>
  </h1>
  <h4> <%=@questions.count%> Question(s) </h4>
  <% @questions.each do |question| %>
    <%= link_to question.title, question_path(question.id) %>
  <% end %>

app/views/welcome/index.html.erb
<h1>Welcome to Quack Overflow</h1>

<%= form_tag("/questions/search", method:"get") do %>
  <%= label_tag(:q, "Search for:") %>
  <%= text_field_tag(:q) %>
  <%= submit_tag("Search") %>
<% end %>

<% if session[:user_id] %>
  <%= link_to "Ask a Question", new_user_question_path(session[:user_id]) %>
<%end %>
<%= link_to "Browse Questions", questions_path %>
<%= link_to "Browse Users", users_path %>